name: $(MajorVersion).$(MinorVersion).$(date:yyMM).$(DayOfMonth)$(rev:rrr)-$(Build.SourceBranchName)

trigger:
  batch: true
  branches:
    include:
      - dev/*
      - test/*
      - main
  tags:
    exclude:
      - '*'

variables:
  - group: GitSSHGroup
  - group: ApiKeys-mm-cloud
  - group: OctoDefault
  - name: frontendPath
    value: 'src/custom-app'
  - name: buildConfiguration
    value: 'Release'
  - name: isRelease
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/r') }}
  - name: isMain
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  - name: isTest
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/test') }}

stages:
  - stage: Build
    jobs:
      - job: frontend
        displayName: Frontend Build
        pool:
          name: meshmakers-ci-agents
        steps:
          - template: update-build-number.yml
          - checkout: self
            clean: true
            submodules: recursive
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: '$(SSHKnownHosts)'
              sshPublicKey: '$(SSHPublicKey)'
              sshPassphrase: '$(SSHPassphrase)'
              sshKeySecureFile: '$(SSHPrivateKeyFile)'
          - task: UseNode@1
            displayName: 'Use Node.js 22.x'
            inputs:
              version: '22.x'
          - script: |
              cd $(frontendPath)
              npm ci
            displayName: 'npm install'
          - script: |
              cd $(frontendPath)
              npm run lint
            displayName: 'Lint'
          - script: |
              cd $(frontendPath)
              npm run test:ci
            displayName: 'Unit Tests'
          - script: |
              cd $(frontendPath)
              npm run build:prod
            displayName: 'Build Production'
          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '$(frontendPath)/test-results/**/*.xml'
            condition: always()
#          - template: build-and-push-docker-image.yml
#            parameters:
#              PublicRegistryServiceConnection: $(DockerRegistryPublicAcrConnection)
#              PrivateRegistryName: $(DockerRegistryPrivateUri)
#              PublicRegistryName: $(DockerRegistryInternalUri)
#              Repository: meshmakers/custom-app
#              Dockerfile: src/custom-app/Dockerfile
          - template: handle-artifacts.yml
