name: $(MajorVersion).$(MinorVersion).$(date:yyMM).$(DayOfMonth)$(rev:rrr)-$(Build.SourceBranchName)

trigger:
  batch: true
  branches:
    include:
      - dev/*
      - test/*
      - main
  tags:
    exclude:
      - '*'

variables:
  - group: GitSSHGroup
  - group: ApiKeys-mm-cloud
  - group: OctoDefault
  - name: isRelease
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/r') }}
  - name: isMain
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}
  - name: isTest
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/test') }}
  - name: OctoLibVersion
    value: 'beta' # overridden at runtime by update-build-number.yml (beta/test/latest)

stages:
  - stage: Build
    jobs:
      - job: frontend
        displayName: Frontend Build
        pool:
          name: meshmakers-ci-agents
        steps:
          - template: update-build-number.yml
          - template: set-version.yml
          - checkout: self
            clean: true
            submodules: recursive
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: '$(SSHKnownHosts)'
              sshPublicKey: '$(SSHPublicKey)'
              sshPassphrase: '$(SSHPassphrase)'
              sshKeySecureFile: '$(SSHPrivateKeyFile)'
          - template: download-ca.yml
          - template: setup-telerik-license.yml
          - template: run-tests.yml
          - template: build-and-push-docker-image.yml
            parameters:
              PublicRegistryServiceConnection: $(DockerRegistryPublicConnection)
              PrivateRegistryName: $(DockerRegistryPrivateUri)
              Repository: meshmakers/custom-app
              Dockerfile: src/custom-app/Dockerfile
          - template: handle-artifacts.yml
