apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "custom-app.fullname" . }}
  labels:
    {{- include "custom-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "custom-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "custom-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "custom-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CONFIG_TENANT_ID
              value: {{ .Values.config.tenantId | quote }}
            - name: CONFIG_API_URL
              value: {{ .Values.config.apiUrl | quote }}
            - name: CONFIG_AUTHORITY_URL
              value: {{ printf "%s/" (trimSuffix "/" .Values.config.authorityUrl) | quote }}
            - name: CONFIG_ASSET_SERVICES_URL
              value: {{ .Values.config.assetServicesUrl | quote }}
            - name: CONFIG_CLIENT_ID
              value: {{ .Values.config.clientId | quote }}
            - name: CONFIG_SCOPE
              value: {{ .Values.config.scope | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
