<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>CustomApp.CkModel</AssemblyName>
        <RootNamespace>CustomApp.CkModel</RootNamespace>
        <Configurations>Debug;Release;DebugL</Configurations>
        <Platforms>AnyCPU</Platforms>
        <OctoPublishCkModel>true</OctoPublishCkModel>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Meshmakers.Octo.Runtime.Contracts" Version="$(OctoVersion)"/>
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.MsBuildTasks" Version="$(OctoVersion)" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <ConstructionKitFolder Visible="false" Include="$(MSBuildProjectDirectory)\ConstructionKit"/>
    </ItemGroup>

</Project>
