const { readFileSync, writeFileSync } = require('fs');
const { resolve } = require('path');

const packageJson = JSON.parse(
  readFileSync(resolve(__dirname, '../../package.json'), 'utf8')
);

const content = `// Auto-generated by version.ts — do not edit manually
export const VERSION = {
  version: '${packageJson.version}',
};
`;

writeFileSync(resolve(__dirname, 'currentVersion.ts'), content, 'utf8');
console.log(`Version file generated: ${packageJson.version}`);
